# Generated by Django 5.1.7 on 2025-04-08 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemlist',
            old_name='Item_name',
            new_name='Category_name',
        ),
        migrations.RemoveField(
            model_name='items',
            name='Category_name',
        ),
        migrations.AddField(
            model_name='items',
            name='Image',
            field=models.ImageField(default='default.jpg', upload_to='items/'),
        ),
        migrations.AlterField(
            model_name='items',
            name='Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Name', to='Base_App.itemlist'),
        ),
    ]
