# Generated by Django 5.1.7 on 2025-04-15 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0007_remove_payment_amount_remove_payment_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='Image',
            field=models.ImageField(default='default.jpg', upload_to='items/'),
        ),
    ]
