# Generated by Django 5.1.7 on 2025-04-15 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0008_feedback_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='Image',
            field=models.ImageField(blank=True, upload_to='items/'),
        ),
    ]
