# Generated by Django 5.1.7 on 2025-04-15 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0009_alter_feedback_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='Description',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='Image',
        ),
    ]
